# DCP Controller Service Installer
# Chapter 1-3: Local Controller ?úÎπÑ?§Ìôî
# 
# Î™©Ï†Å: OpenClaw ControllerÎ•??àÏ†ï?ÅÏù∏ Windows ?úÎπÑ?§Î°ú Î≥Ä??
# Î∞©Ïãù: Task Scheduler + Watchdog ?µÌï©

param(
    [switch]$Uninstall = $false,
    [switch]$Restart = $false
)

$ErrorActionPreference = "Stop"

# Í≤ΩÎ°ú ?§Ï†ï
$ControllerPath = "C:\OpenClaw\controller"
$ScriptPath = "$ControllerPath\openclaw_controller.ps1"
$TaskName = "DCP Controller Service"
$LogPath = "C:\OpenClaw\logs"

Write-Host "`n=== DCP Controller Service Installer ===" -ForegroundColor Cyan
Write-Host "Time: $(Get-Date -Format 'HH:mm:ss')`n"

# ?úÍ±∞ Î™®Îìú
if ($Uninstall) {
    Write-Host "[Uninstall] Removing Controller Service..." -ForegroundColor Yellow
    
    # Task Ï§ëÏ? Î∞??úÍ±∞
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "  Task removed." -ForegroundColor Green
    }
    else {
        Write-Host "  No task found." -ForegroundColor Gray
    }
    
    # ?ÑÎ°ú?∏Ïä§ Ï¢ÖÎ£å
    Get-Process -Name powershell -ErrorAction SilentlyContinue | 
    Where-Object { $_.CommandLine -like "*openclaw_controller.ps1*" } | 
    Stop-Process -Force -ErrorAction SilentlyContinue
    
    Write-Host "`nUninstall complete.`n" -ForegroundColor Green
    exit 0
}

# ?¨Ïãú??Î™®Îìú
if ($Restart) {
    Write-Host "[Restart] Restarting Controller Service..." -ForegroundColor Yellow
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    Start-ScheduledTask -TaskName $TaskName
    Start-Sleep -Seconds 3
    
    # ?ÅÌÉú ?ïÏù∏
    $portTest = Test-NetConnection -ComputerName 127.0.0.1 -Port 17777 -WarningAction SilentlyContinue -ErrorAction SilentlyContinue
    if ($portTest.TcpTestSucceeded) {
        Write-Host "  Controller restarted successfully on port 17777" -ForegroundColor Green
    }
    else {
        Write-Host "  Warning: Port 17777 not responding" -ForegroundColor Yellow
    }
    exit 0
}

# ?§Ïπò Î™®Îìú
Write-Host "[1/5] Checking prerequisites..." -NoNewline

# Controller ?§ÌÅ¨Î¶ΩÌä∏ ?ïÏù∏
if (-not (Test-Path $ScriptPath)) {
    Write-Host " FAIL" -ForegroundColor Red
    Write-Host "Error: openclaw_controller.ps1 not found at $ControllerPath" -ForegroundColor Red
    exit 1
}

# Î°úÍ∑∏ ?îÎ†â?†Î¶¨ ?ùÏÑ±
if (-not (Test-Path $LogPath)) {
    New-Item -ItemType Directory -Path $LogPath -Force | Out-Null
}

Write-Host " OK" -ForegroundColor Green

# Í∏∞Ï°¥ Task ?úÍ±∞
Write-Host "[2/5] Removing old tasks..." -NoNewline
$oldTasks = @("OpenClaw Controller", "OpenClawLocalController", $TaskName)
foreach ($oldTask in $oldTasks) {
    $task = Get-ScheduledTask -TaskName $oldTask -ErrorAction SilentlyContinue
    if ($task) {
        Stop-ScheduledTask -TaskName $oldTask -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 1
        Unregister-ScheduledTask -TaskName $oldTask -Confirm:$false -ErrorAction SilentlyContinue
    }
}
Write-Host " OK" -ForegroundColor Green

# Wrapper ?§ÌÅ¨Î¶ΩÌä∏ ?ùÏÑ±
Write-Host "[3/5] Creating service wrapper..." -NoNewline

$WrapperPath = "$ControllerPath\dcp_controller_wrapper.ps1"
$WrapperContent = @"
# DCP Controller Service Wrapper
# Auto-generated by Install-DCP-Controller.ps1

`$ErrorActionPreference = "Continue"
`$LogFile = "C:\OpenClaw\logs\controller_service_`$(Get-Date -Format 'yyyyMMdd').log"

function Write-ServiceLog {
    param([string]`$Message)
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    `$logMessage = "[`$timestamp] `$Message"
    Add-Content -Path `$LogFile -Value `$logMessage
}

Write-ServiceLog "========================================="
Write-ServiceLog "DCP Controller Service Starting"
Write-ServiceLog "PID: `$PID"
Write-ServiceLog "========================================="

try {
    # Controller ?§Ìñâ
    `$scriptPath = "C:\OpenClaw\controller\openclaw_controller.ps1"
    Write-ServiceLog "Loading controller: `$scriptPath"
    
    # ?¨Ìä∏ 17777Í≥?18082?êÏÑú HTTP ?úÎ≤Ñ ?úÏûë
    & `$scriptPath
    
} catch {
    Write-ServiceLog "ERROR: `$(`$_.Exception.Message)"
    Write-ServiceLog "Stack: `$(`$_.ScriptStackTrace)"
    throw
} finally {
    Write-ServiceLog "DCP Controller Service Stopped"
}
"@

Set-Content -Path $WrapperPath -Value $WrapperContent -Encoding UTF8
Write-Host " OK" -ForegroundColor Green

# Task Scheduler ?±Î°ù
Write-Host "[4/5] Registering Task Scheduler..." -NoNewline

$Action = New-ScheduledTaskAction `
    -Execute "PowerShell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$WrapperPath`""

$Trigger = New-ScheduledTaskTrigger -AtStartup

$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive

$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 5 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Days 365)

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $Action `
    -Trigger $Trigger `
    -Principal $Principal `
    -Settings $Settings `
    -Description "DCP ?µÌï©Í¥Ä??- Local Controller API (?¨Ìä∏ 17777, 18082)" `
    -Force | Out-Null

Write-Host " OK" -ForegroundColor Green

# ?úÎπÑ???úÏûë
Write-Host "[5/5] Starting Controller Service..." -NoNewline

Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 5

# Health Check
$healthCheck = $false
for ($i = 1; $i -le 10; $i++) {
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:17777/health" -Method GET -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
        if ($response.StatusCode -eq 200) {
            $healthCheck = $true
            break
        }
    }
    catch {}
    Start-Sleep -Seconds 1
}

if ($healthCheck) {
    Write-Host " OK" -ForegroundColor Green
}
else {
    Write-Host " WARNING" -ForegroundColor Yellow
    Write-Host "`n  Port 17777 not responding yet. Check logs:" -ForegroundColor Yellow
    Write-Host "  $LogPath\controller_service_$(Get-Date -Format 'yyyyMMdd').log`n" -ForegroundColor Gray
}

# Í≤∞Í≥º Ï∂úÎ†•
Write-Host "`n=== Installation Complete ===" -ForegroundColor Cyan

$taskInfo = Get-ScheduledTask -TaskName $TaskName
Write-Host "`nTask Status: $($taskInfo.State)" -ForegroundColor $(if ($taskInfo.State -eq 'Running') { 'Green' } else { 'Yellow' })

Write-Host "`nEndpoints:" -ForegroundColor Cyan
Write-Host "  http://127.0.0.1:17777/health" -ForegroundColor Gray
Write-Host "  http://127.0.0.1:18082/exec" -ForegroundColor Gray
Write-Host "  http://127.0.0.1:18082/kill" -ForegroundColor Gray

Write-Host "`nManagement Commands:" -ForegroundColor Cyan
Write-Host "  Start:   Start-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Gray
Write-Host "  Stop:    Stop-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Gray
Write-Host "  Restart: .\Install-DCP-Controller.ps1 -Restart" -ForegroundColor Gray
Write-Host "  Remove:  .\Install-DCP-Controller.ps1 -Uninstall" -ForegroundColor Gray

Write-Host "`nLogs:" -ForegroundColor Cyan
Write-Host "  $LogPath\controller_service_$(Get-Date -Format 'yyyyMMdd').log`n" -ForegroundColor Gray

# systems.yaml ?ÖÎç∞?¥Ìä∏ ?àÎÇ¥
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Update Start-All.ps1 to use this task" -ForegroundColor Yellow
Write-Host "  2. Install Watchdog (Install-DCP-Watchdog.ps1)" -ForegroundColor Yellow
Write-Host "  3. Test with: C:\UCONAI-LLM\scripts\health\health-all.ps1`n" -ForegroundColor Yellow
