# DCP Controller Service Wrapper
# Auto-generated by Install-DCP-Controller.ps1

$ErrorActionPreference = "Continue"
$LogFile = "C:\OpenClaw\logs\controller_service_$(Get-Date -Format 'yyyyMMdd').log"

function Write-ServiceLog {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] $Message"
    Add-Content -Path $LogFile -Value $logMessage
}

Write-ServiceLog "========================================="
Write-ServiceLog "DCP Controller Service Starting"
Write-ServiceLog "PID: $PID"
Write-ServiceLog "========================================="

try {
    # Controller ?ㅽ뻾
    $scriptPath = "C:\OpenClaw\controller\openclaw_controller.ps1"
    Write-ServiceLog "Loading controller: $scriptPath"
    
    # ?ы듃 17777怨?18082?먯꽌 HTTP ?쒕쾭 ?쒖옉
    & $scriptPath
    
} catch {
    Write-ServiceLog "ERROR: $($_.Exception.Message)"
    Write-ServiceLog "Stack: $($_.ScriptStackTrace)"
    throw
} finally {
    Write-ServiceLog "DCP Controller Service Stopped"
}
